name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case: ['en/eiti', 'en/meil', 'pl/eiti', 'pl/meil']
      fail-fast: false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y    \
               biber                 \
               latexmk               \
               poppler-utils         \
               scons                 \
               texlive               \
               texlive-bibtex-extra  \
               texlive-fonts-extra   \
               texlive-latex-extra   \
               texlive-lang-polish   \
               texlive-luatex        \
               texlive-xetex         \
               tex-gyre

      - name: Checkout WUT-Thesis repository
        uses: actions/checkout@v2

      - name: Generate PDF file
        run: cp test/${{matrix.test-case}}/main.textest main.tex && scons pdf

      - name: Verify build with referential text
        run: scons test ref=test/${{matrix.test-case}}/ref.txt
